
# 完整的构建模板标签说明：https://lark.alipay.com/mq4l6o/val2ny/prwhsh
# version表示构建模板.fw.yml的版本，默认值为1.0
version: 1.0
# name表示当前代码仓库的模块名称
name: aliyun-assist

# machine表示编译机配置，container表示基于docker容器编译
# 5u7_docker表示宿主机的装机模板是alios5的
# 'reg.docker.alibaba-inc.com/scm/buildbox5u7:latest'表示编译使用的base镜像，用户可使用自定义的编译镜像
machine:
  container:
    5u7_docker:
      - reg.docker.alibaba-inc.com/scm/buildbox_ubuntu16_i386

#dependencies:
 # other:
  #  -  pip install aliyun-python-sdk-ecs
  #  -  pip install aliyun-python-sdk-core
# scripts中定义构建命令行，通过定义的构建命令行可以构建出artifacts中定义的构建产物
# 在scripts中可直接使用系统环境变量
scripts:
  - echo {{FW_BUILD_NUMBER}} > fastwork/aone_version
  - python ./fastwork/build.py

# artifacts定义构建产物类型
artifacts:
  packages:
    - fastwork/zip/linux_update_.*.zip
    - fastwork/deb/aliyun_assist_.*.deb
    - fastwork/rpm/aliyun_assist_.*.rpm

# notifications定义通知人员列表，目前只支持邮件通知
notifications:
  email: 
    - shusong.lss@alibaba-inc.com
    - quanju.xqj@alibaba-inc.com